#name: tip-calculator

services:

  unifi-app:
    image: 'node:26-trixie'
    working_dir: /app
    command:
      - sleep
      - infinity
#    command:
#      - npm
#      - run
#      - dev
#      - --
#      - --host
#      - 0.0.0.0
    stdin_open: true
    tty: true
    ports:
      - "3300:3000"
    volumes:
      - './app:/app'
    environment:
      UNIFI_API_KEY_FILE: /run/secrets/unifi_api_key
    secrets:
      - unifi_api_key
    restart: unless-stopped
    networks: [niteowl-dev]

secrets:
  unifi_api_key:
    file: ./secrets/unifi_api_key

networks:
  niteowl-dev:
    name: niteowl-dev
    external: true
