/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as ToastReadinessRouteImport } from './routes/toast-readiness'
import { Route as ZonesRouteImport } from './routes/zones'
import { Route as ApiDevicesRouteImport } from './routes/api/devices'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as ApiToastPolicyRouteImport } from './routes/api/toast-policy'
import { Route as ApiZonesRouteImport } from './routes/api/zones'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const ToastReadinessRoute = ToastReadinessRouteImport.update({
  id: '/toast-readiness',
  path: '/toast-readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesRoute = ZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevicesRoute = ApiDevicesRouteImport.update({
  id: '/api/devices',
  path: '/api/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToastPolicyRoute = ApiToastPolicyRouteImport.update({
  id: '/api/toast-policy',
  path: '/api/toast-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZonesRoute = ApiZonesRouteImport.update({
  id: '/api/zones',
  path: '/api/zones',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/devices': typeof DevicesRoute
  '/toast-readiness': typeof ToastReadinessRoute
  '/zones': typeof ZonesRoute
  '/api/devices': typeof ApiDevicesRoute
  '/api/status': typeof ApiStatusRoute
  '/api/toast-policy': typeof ApiToastPolicyRoute
  '/api/zones': typeof ApiZonesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/devices': typeof DevicesRoute
  '/toast-readiness': typeof ToastReadinessRoute
  '/zones': typeof ZonesRoute
  '/api/devices': typeof ApiDevicesRoute
  '/api/status': typeof ApiStatusRoute
  '/api/toast-policy': typeof ApiToastPolicyRoute
  '/api/zones': typeof ApiZonesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/devices': typeof DevicesRoute
  '/toast-readiness': typeof ToastReadinessRoute
  '/zones': typeof ZonesRoute
  '/api/devices': typeof ApiDevicesRoute
  '/api/status': typeof ApiStatusRoute
  '/api/toast-policy': typeof ApiToastPolicyRoute
  '/api/zones': typeof ApiZonesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/devices'
    | '/toast-readiness'
    | '/zones'
    | '/api/devices'
    | '/api/status'
    | '/api/toast-policy'
    | '/api/zones'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/devices'
    | '/toast-readiness'
    | '/zones'
    | '/api/devices'
    | '/api/status'
    | '/api/toast-policy'
    | '/api/zones'
  id:
    | '__root__'
    | '/'
    | '/devices'
    | '/toast-readiness'
    | '/zones'
    | '/api/devices'
    | '/api/status'
    | '/api/toast-policy'
    | '/api/zones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevicesRoute: typeof DevicesRoute
  ToastReadinessRoute: typeof ToastReadinessRoute
  ZonesRoute: typeof ZonesRoute
  ApiDevicesRoute: typeof ApiDevicesRoute
  ApiStatusRoute: typeof ApiStatusRoute
  ApiToastPolicyRoute: typeof ApiToastPolicyRoute
  ApiZonesRoute: typeof ApiZonesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toast-readiness': {
      id: '/toast-readiness'
      path: '/toast-readiness'
      fullPath: '/toast-readiness'
      preLoaderRoute: typeof ToastReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones': {
      id: '/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof ZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/devices': {
      id: '/api/devices'
      path: '/api/devices'
      fullPath: '/api/devices'
      preLoaderRoute: typeof ApiDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/toast-policy': {
      id: '/api/toast-policy'
      path: '/api/toast-policy'
      fullPath: '/api/toast-policy'
      preLoaderRoute: typeof ApiToastPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zones': {
      id: '/api/zones'
      path: '/api/zones'
      fullPath: '/api/zones'
      preLoaderRoute: typeof ApiZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevicesRoute: DevicesRoute,
  ToastReadinessRoute: ToastReadinessRoute,
  ZonesRoute: ZonesRoute,
  ApiDevicesRoute: ApiDevicesRoute,
  ApiStatusRoute: ApiStatusRoute,
  ApiToastPolicyRoute: ApiToastPolicyRoute,
  ApiZonesRoute: ApiZonesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
