import { useEffect, useState } from "react"
import { createFileRoute } from "@tanstack/react-router"
import { BatteryChargingIcon, CableIcon, CircleCheckIcon, CircleDotIcon, CircleHelpIcon, EthernetPortIcon, NetworkIcon, RadioTowerIcon, RefreshCwIcon, RouterIcon, ServerIcon, WifiIcon } from "lucide-react"
import { Badge } from "#/components/ui/badge.tsx"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "#/components/ui/card.tsx"
import { Skeleton } from "#/components/ui/skeleton.tsx"
import { authBaseURL, authClient, networkStatusApiFetch } from "#/lib/auth-client.ts"

export const Route = createFileRoute("/devices")({
  head: () => ({ meta: [{ title: "UniFi Network Devices" }] }),
  component: DevicesPage,
})
type Device = { id: string; name: string; model: string; category: "gateway" | "access-point" | "switch" | "console" | "lte" | "ups" | "other"; ipAddress: string | null; macAddress: string | null; firmwareVersion: string | null; firmwareStatus: "update-available" | "up-to-date" | "unknown"; firmwareAvailableVersion?: string | null; state: number | null; online: boolean; adopted: boolean | null; uplink: { name: string; macAddress: string | null; port: number | null } | null; imageUrl?: string | null }
type DeviceSite = { id: string; name: string; available: boolean; devices: Device[] }
type DevicesResponse = { updatedAt: string; sites: DeviceSite[]; error?: string }
function DeviceIcon({ category }: { category: Device["category"] }) { const Icon = category === "gateway" ? RouterIcon : category === "access-point" ? WifiIcon : category === "switch" ? EthernetPortIcon : category === "lte" ? RadioTowerIcon : category === "ups" ? BatteryChargingIcon : ServerIcon; return <Icon className="size-8" /> }
function DeviceArtwork({ device }: { device: Device }) { const [failed, setFailed] = useState(false); return <div className="flex size-20 shrink-0 items-center justify-center rounded-xl border bg-muted/30 text-muted-foreground">{device.imageUrl && !failed ? <img src={device.imageUrl} alt={`${device.model} hardware`} className="size-[4.5rem] object-contain" loading="lazy" onError={() => setFailed(true)} /> : <DeviceIcon category={device.category} />}</div> }
function DetailRow({ label, value }: { label: string; value: string | null }) { return <div className="grid grid-cols-[5.5rem_minmax(0,1fr)] gap-3 text-sm"><span className="text-muted-foreground">{label}</span><span className="min-w-0 break-all font-medium">{value || "—"}</span></div> }
function FirmwareBadge({ status, availableVersion }: { status: Device["firmwareStatus"]; availableVersion?: string | null }) { if (status === "update-available") return <Badge variant="outline" className="shrink-0 whitespace-nowrap"><RefreshCwIcon />{availableVersion ? `Firmware ${availableVersion} available` : "Firmware update available"}</Badge>; if (status === "up-to-date") return <Badge variant="outline" className="shrink-0 whitespace-nowrap"><CircleCheckIcon />Firmware up to date</Badge>; return <Badge variant="outline" className="shrink-0 whitespace-nowrap"><CircleHelpIcon />Firmware status unknown</Badge> }
function FirmwareRow({ device }: { device: Device }) { return <div className="grid grid-cols-[5.5rem_minmax(0,1fr)] gap-3 text-sm"><span className="text-muted-foreground">Firmware</span><div className="flex min-w-0 flex-nowrap items-center gap-2"><span className="shrink-0 font-medium">{device.firmwareVersion || "—"}</span><FirmwareBadge status={device.firmwareStatus} availableVersion={device.firmwareAvailableVersion} /></div></div> }
function DeviceCard({ device }: { device: Device }) { return <Card className="min-w-0 overflow-hidden"><CardHeader className="pb-4"><div className="flex items-start gap-4"><DeviceArtwork device={device} /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><div className="min-w-0"><CardTitle className="truncate text-lg">{device.name}</CardTitle><CardDescription className="mt-1">{device.model}</CardDescription></div><Badge variant={device.online ? "secondary" : "destructive"}><CircleDotIcon />{device.online ? "Online" : "Offline"}</Badge></div></div></div></CardHeader><CardContent className="space-y-3"><DetailRow label="IP address" value={device.ipAddress} /><DetailRow label="MAC" value={device.macAddress} /><FirmwareRow device={device} />{device.uplink ? <DetailRow label="Uplink" value={`${device.uplink.name}${device.uplink.port ? ` · Port ${device.uplink.port}` : ""}`} /> : null}</CardContent></Card> }
function LoadingPage() { return <main className="flex-1 p-4 md:p-6"><div className="space-y-6"><div className="flex items-start gap-3"><Skeleton className="size-10 rounded-full" /><div className="space-y-2"><Skeleton className="h-8 w-40" /><Skeleton className="h-4 w-80 max-w-full" /></div></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Skeleton className="h-64 rounded-xl" /></div></div></main> }
function DevicesPage() {
  const { data: session, isPending } = authClient.useSession()
  const { data: activeOrganization, isPending: organizationPending } = authClient.useActiveOrganization()
  const [data, setData] = useState<DevicesResponse | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true)
  useEffect(() => { if (isPending || session) return; const redirectTo = encodeURIComponent(window.location.href); window.location.replace(`${authBaseURL.replace(/\/$/, "")}/auth/sign-in?redirectTo=${redirectTo}`) }, [isPending, session])
  useEffect(() => {
    if (!session || !activeOrganization?.id) return
    let cancelled = false; setLoading(true); setData(null)
    async function loadDevices() { try { const params = new URLSearchParams({ organizationId: activeOrganization!.id }); const response = await networkStatusApiFetch(`/api/devices?${params}`, { headers: { Accept: "application/json" } }); const body = (await response.json()) as DevicesResponse; if (!response.ok) throw new Error(body.error ?? "Unable to load UniFi devices"); if (!cancelled) { setData(body); setError(null); setLoading(false) } } catch (caught) { if (!cancelled) { setError(caught instanceof Error ? caught.message : "Unable to load UniFi devices"); setLoading(false) } } }
    void loadDevices(); const timer = window.setInterval(() => void loadDevices(), 30_000); return () => { cancelled = true; window.clearInterval(timer) }
  }, [activeOrganization?.id, session])
  if (isPending || organizationPending || (session && activeOrganization && loading)) return <LoadingPage />
  if (!session) return null
  if (!activeOrganization) return <main className="flex-1 p-4 md:p-6"><Card><CardHeader><CardTitle>Select an organization</CardTitle><CardDescription>Choose an organization to view its UniFi devices.</CardDescription></CardHeader></Card></main>
  return <main className="flex-1 p-4 md:p-6"><div className="w-full space-y-8"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div className="flex items-start gap-3"><div className="flex size-10 shrink-0 items-center justify-center rounded-full border bg-card text-muted-foreground shadow-sm"><CableIcon className="size-5" /></div><div><h1 className="text-2xl font-semibold tracking-tight">UniFi Network Devices</h1><p className="mt-1 text-sm text-muted-foreground">UniFi equipment inventory, addressing, and firmware status for the selected organization.</p></div></div><Badge variant={error ? "destructive" : "outline"} className="w-fit"><NetworkIcon />{error ? error : data?.updatedAt ? `Updated ${new Date(data.updatedAt).toLocaleTimeString()}` : "Connecting to UniFi"}</Badge></div>{data?.sites.map((site) => <section key={site.id} className="space-y-3"><div className="flex items-center justify-between gap-3"><div><h2 className="text-lg font-semibold tracking-tight">{site.name}</h2><p className="text-sm text-muted-foreground">{site.available ? `${site.devices.length} UniFi device${site.devices.length === 1 ? "" : "s"}` : "Console unavailable"}</p></div></div>{site.devices.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{site.devices.map((device) => <DeviceCard key={device.id} device={device} />)}</div> : <Card><CardHeader><CardTitle>No devices available</CardTitle><CardDescription>{site.available ? "This UniFi site did not return adopted devices." : "The UniFi Network console could not be reached through the Fabric connector."}</CardDescription></CardHeader></Card>}</section>)}{!data?.sites.length ? <Card><CardHeader><CardTitle>Device inventory unavailable</CardTitle><CardDescription>{error ?? "No configured UniFi site was returned."}</CardDescription></CardHeader></Card> : null}</div></main>
}
